[package]
name = "transform-editor"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "=0.3.8"
notify = { git = "https://github.com/notify-rs/notify", rev = "75f8bd9304" }
